swagger: "2.0"
info:
  title: Whatever
  version: 1.0.0
host: localhost:1234
schemes:
  - http
definitions:
  Bar:
    type: string
    enum:
      - v1
      - v2
      - i like spaces
paths:
  /foo:
    get:
      operationId: getFoo
      parameters:
      - name: CustomHeader
        in: header
        type: string
        x-scala-type: Bar
        required: true
      responses:
        '200':
          description: OK
        '404':
          description: Not found
